apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv-shir
  name: use-pv-shir
spec:
  containers:
  - image: nginx
    name: use-pv-shir
    resources: {}
    volumeMounts:
    - name: pv-1
      mountPath: "/data"
  volumes:
  - name: pv-1
    persistentVolumeClaim:
      claimName: pv-1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
