apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - name: nginx-deploy
        image: nginx:1.17
        resources: {}
        ports:
        - containerPort: 86

# to record the changes I run: kubectl apply -f 13-nginx-deploy.yaml  --record
