apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  labels:
    name: nginx-resolver
spec:
  containers:
  - name: nginx-resolver
    image: nginx
    resources: {}
    ports:
      - containerPort: 90

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
spec:
  selector:
    app: nginx-resolver
  ports:
  - port: 90
    targetPort: 90

