apiVersion: v1
kind: Pod
metadata:
  name: nginx-critical
  labels:
    name: nginx-critical
spec:
  nodeName: k3d-k3s-default-server-0
  containers:
  - name: nginx-critical
    image: nginx
    resources: {}
    ports:
      - containerPort: 91
  restartPolicy: Always
