apiVersion: v1
kind: Service
metadata:
  labels:
    app: messaging-service
  name: messaging-service
spec:
  ports:
  - name: 6379-8080
    port: 6379
    protocol: TCP
    targetPort: 8080
  selector:
    app: messaging-service
  type: ClusterIP
status:
  loadBalancer: {}