apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
spec:
  nodeName: k3d-k3s-default-server-0
  containers:
  - name: busybox-container
    image: busybox
    command: ["sleep", "1000"]
  restartPolicy: Always

