apiVersion: v1
kind: Namespace
metadata:
  name: finance-shir

---

apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance-shir
  labels:
    name: temp-bus
spec:
  containers:
  - name: temp-bus
    image: redis:alpine
    resources: {}
    ports:
      - containerPort: 84
