apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-shir
  labels:
    name: nginx-pod-shir
spec:
  containers:
  - name: nginx-pod-shir
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
