apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "5"
      deployment.kubernetes.io/max-replicas: "7"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2024-01-20T15:17:52Z"
    generation: 1
    labels:
      app: webapp
      pod-template-hash: "8474645868"
    name: webapp-8474645868
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: webapp
      uid: 192c557f-2f78-4611-99d8-f31ff08f189f
    resourceVersion: "9091"
    uid: 03295db2-cfcf-4f3e-8770-6992e7fca541
  spec:
    replicas: 5
    selector:
      matchLabels:
        app: webapp
        pod-template-hash: "8474645868"
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: webapp
          pod-template-hash: "8474645868"
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 5
    fullyLabeledReplicas: 5
    observedGeneration: 1
    readyReplicas: 5
    replicas: 5
kind: List
metadata:
  resourceVersion: ""
